apiVersion: rbac.authorization.k8s.io/v1
# We use 'Role' here because editing should be restricted to a specific namespace.
kind: Role
metadata:
  # The name doesn't need a namespace as it will be applied within one.
  name: autopeer-editor
rules:
