resources:
  - ../../base
  - ../../components/cpeer-controller-manager/overlays/dev
  - ../../components/cpeer-hub/overlays/dev
  - ../../components/emqx/overlays/dev
  - ../../components/minio/overlays/dev
