apiVersion: v1
kind: Service
metadata:
  name: controller-metrics-service
spec:
  selector:
    app.kubernetes.io/name: autopeer-controller
  ports:
  - name: https
    port: 8443 # Default port for Prometheus metrics when TLS is enabled
    targetPort: https
    protocol: TCP
  - name: health
    port: 9001
    targetPort: health
    protocol: TCP