apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: autopeer-io

resources:
- ../../base

# 添加通用标签
labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/part-of: autopeer
    env: dev