apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Inherit all resources from the base
resources:
- ../../base

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: autopeer
