---
# Source: emqx/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: emqx
  namespace: cloupeer-system
  labels:
    app.kubernetes.io/name: emqx
    helm.sh/chart: emqx-5.8.8
    app.kubernetes.io/instance: emqx
    app.kubernetes.io/managed-by: Helm
---
# Source: emqx/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: emqx-env
  namespace: cloupeer-system
  labels:
    app.kubernetes.io/name: emqx
    helm.sh/chart: emqx-5.8.8
    app.kubernetes.io/instance: emqx
    app.kubernetes.io/managed-by: Helm
data:
  EMQX_NAME:  emqx
  EMQX_CLUSTER__DNS__NAME: "emqx-headless.cloupeer-system.svc.cluster.local"
  EMQX_CLUSTER__DNS__RECORD_TYPE: "srv"
  EMQX_CLUSTER__DISCOVERY_STRATEGY: "dns"
  EMQX_DASHBOARD__DEFAULT_PASSWORD: "public"
  EMQX_DASHBOARD__DEFAULT_USERNAME: "admin"
---
# Source: emqx/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: emqx
  namespace: cloupeer-system
  labels:
    app.kubernetes.io/name: emqx
    helm.sh/chart: emqx-5.8.8
    app.kubernetes.io/instance: emqx
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: mqtt
    nodePort: null
  - name: mqttssl
    port: 8883
    protocol: TCP
    targetPort: mqttssl
    nodePort: null
  - name: ws
    port: 8083
    protocol: TCP
    targetPort: ws
    nodePort: null
  - name: wss
    port: 8084
    protocol: TCP
    targetPort: wss
    nodePort: null
  - name: dashboard
    port: 18083
    protocol: TCP
    targetPort: dashboard
    nodePort: null
  selector:
    app.kubernetes.io/name: emqx
    app.kubernetes.io/instance: emqx
---
# Source: emqx/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: emqx-headless
  namespace: cloupeer-system
  labels:
    app.kubernetes.io/name: emqx
    helm.sh/chart: emqx-5.8.8
    app.kubernetes.io/instance: emqx
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  sessionAffinity: None
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: mqtt
  - name: mqttssl
    port: 8883
    protocol: TCP
    targetPort: mqttssl
  - name: ws
    port: 8083
    protocol: TCP
    targetPort: ws
  - name: wss
    port: 8084
    protocol: TCP
    targetPort: wss
  - name: dashboard
    port: 18083
    protocol: TCP
    targetPort: dashboard
  - name: ekka
    port: 4370
    protocol: TCP
    targetPort: ekka
  selector:
    app.kubernetes.io/name: emqx
    app.kubernetes.io/instance: emqx
---
# Source: emqx/templates/StatefulSet.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: emqx
  namespace: cloupeer-system
  labels:
    app.kubernetes.io/name: emqx
    helm.sh/chart: emqx-5.8.8
    app.kubernetes.io/instance: emqx
    app.kubernetes.io/managed-by: Helm
spec:
  serviceName: emqx-headless
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: emqx
      app.kubernetes.io/instance: emqx
  template:
    metadata:
      labels:
        app: emqx
        version: 5.8.8
        app.kubernetes.io/name: emqx
        app.kubernetes.io/instance: emqx
      annotations:
    spec:
      serviceAccountName: emqx
      volumes:
      - name: emqx-data
        emptyDir: {}
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: Always
        runAsUser: 1000
        supplementalGroups:
        - 1000
      containers:
        - name: emqx
          image: "emqx/emqx:5.8.8"
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
          ports:
          - name: mqtt
            containerPort: 1883
          - name: mqttssl
            containerPort: 8883
          - name: ws
            containerPort: 8083
          - name: wss
            containerPort: 8084
          - name: dashboard
            containerPort: 18083
          - name: ekka
            containerPort: 4370
          - name: genrpc-manual
            containerPort: 5369
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: EMQX_HOST
            value: $(POD_NAME).emqx-headless.cloupeer-system.svc.cluster.local
          envFrom:
            - configMapRef:
                name: emqx-env
          resources:
            {}
          volumeMounts:
          - name: emqx-data
            mountPath: "/opt/emqx/data"
          
          readinessProbe:
            httpGet:
              path: /status
              port: 18083
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /status
              port: 18083
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 10
---
# Source: emqx/templates/rbac.yaml
---
