apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  annotations:
    # 允许上传大文件 (固件包)
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "autopeer-prod-issuer"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - s3.autopeer.io
        - minio.autopeer.io
      secretName: minio-tls
  rules:
    - host: s3.autopeer.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9000
    - host: minio.autopeer.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9001